/* 
 * SessionService documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Cloud.ASR.Client.SwaggerDateConverter;

namespace Cloud.ASR.Model
{
    /// <summary>
    /// Object for module names transport
    /// </summary>
    [DataContract]
    public partial class ModuleNamesDto :  IEquatable<ModuleNamesDto>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ModuleNamesDto" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ModuleNamesDto() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ModuleNamesDto" /> class.
        /// </summary>
        /// <param name="Names">Module names (required).</param>
        public ModuleNamesDto(List<string> Names = default(List<string>))
        {
            // to ensure "Names" is required (not null)
            if (Names == null)
            {
                throw new InvalidDataException("Names is a required property for ModuleNamesDto and cannot be null");
            }
            else
            {
                this.Names = Names;
            }
        }
        
        /// <summary>
        /// Module names
        /// </summary>
        /// <value>Module names</value>
        [DataMember(Name="names", EmitDefaultValue=false)]
        public List<string> Names { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ModuleNamesDto {\n");
            sb.Append("  Names: ").Append(Names).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ModuleNamesDto);
        }

        /// <summary>
        /// Returns true if ModuleNamesDto instances are equal
        /// </summary>
        /// <param name="input">Instance of ModuleNamesDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ModuleNamesDto input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Names == input.Names ||
                    this.Names != null &&
                    this.Names.SequenceEqual(input.Names)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Names != null)
                    hashCode = hashCode * 59 + this.Names.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
