/* 
 * SessionService documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Cloud.TTS.Client;
using Cloud.TTS.Model;

namespace Cloud.TTS.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISessionApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Check session state
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <returns>AuthStatusDto</returns>
        AuthStatusDto Check (Guid? xSessionID);

        /// <summary>
        /// Check session state
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <returns>ApiResponse of AuthStatusDto</returns>
        ApiResponse<AuthStatusDto> CheckWithHttpInfo (Guid? xSessionID);
        /// <summary>
        /// Get All domains for auth without session
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>DomainDto</returns>
        DomainDto GetDomains ();

        /// <summary>
        /// Get All domains for auth without session
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of DomainDto</returns>
        ApiResponse<DomainDto> GetDomainsWithHttpInfo ();
        /// <summary>
        /// Get current user privileges
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <param name="body">Module names</param>
        /// <returns>Dictionary&lt;string, Object&gt;</returns>
        Dictionary<string, Object> GetGrantedPrivileges (Guid? xSessionID, ModuleNamesDto body);

        /// <summary>
        /// Get current user privileges
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <param name="body">Module names</param>
        /// <returns>ApiResponse of Dictionary&lt;string, Object&gt;</returns>
        ApiResponse<Dictionary<string, Object>> GetGrantedPrivilegesWithHttpInfo (Guid? xSessionID, ModuleNamesDto body);
        /// <summary>
        /// Log in to system and obtain session identifier. Pass sessionId in &#39;X-Session-ID&#39; header in all other API requests
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="credentials">User&#39;s credentials</param>
        /// <returns>AuthResponseDto</returns>
        AuthResponseDto Login (AuthRequestDto credentials);

        /// <summary>
        /// Log in to system and obtain session identifier. Pass sessionId in &#39;X-Session-ID&#39; header in all other API requests
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="credentials">User&#39;s credentials</param>
        /// <returns>ApiResponse of AuthResponseDto</returns>
        ApiResponse<AuthResponseDto> LoginWithHttpInfo (AuthRequestDto credentials);
        /// <summary>
        /// Log out of system
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <returns></returns>
        void Logout (Guid? xSessionID);

        /// <summary>
        /// Log out of system
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> LogoutWithHttpInfo (Guid? xSessionID);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Check session state
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <returns>Task of AuthStatusDto</returns>
        System.Threading.Tasks.Task<AuthStatusDto> CheckAsync (Guid? xSessionID);

        /// <summary>
        /// Check session state
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <returns>Task of ApiResponse (AuthStatusDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<AuthStatusDto>> CheckAsyncWithHttpInfo (Guid? xSessionID);
        /// <summary>
        /// Get All domains for auth without session
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of DomainDto</returns>
        System.Threading.Tasks.Task<DomainDto> GetDomainsAsync ();

        /// <summary>
        /// Get All domains for auth without session
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (DomainDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<DomainDto>> GetDomainsAsyncWithHttpInfo ();
        /// <summary>
        /// Get current user privileges
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <param name="body">Module names</param>
        /// <returns>Task of Dictionary&lt;string, Object&gt;</returns>
        System.Threading.Tasks.Task<Dictionary<string, Object>> GetGrantedPrivilegesAsync (Guid? xSessionID, ModuleNamesDto body);

        /// <summary>
        /// Get current user privileges
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <param name="body">Module names</param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, Object&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<Dictionary<string, Object>>> GetGrantedPrivilegesAsyncWithHttpInfo (Guid? xSessionID, ModuleNamesDto body);
        /// <summary>
        /// Log in to system and obtain session identifier. Pass sessionId in &#39;X-Session-ID&#39; header in all other API requests
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="credentials">User&#39;s credentials</param>
        /// <returns>Task of AuthResponseDto</returns>
        System.Threading.Tasks.Task<AuthResponseDto> LoginAsync (AuthRequestDto credentials);

        /// <summary>
        /// Log in to system and obtain session identifier. Pass sessionId in &#39;X-Session-ID&#39; header in all other API requests
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="credentials">User&#39;s credentials</param>
        /// <returns>Task of ApiResponse (AuthResponseDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<AuthResponseDto>> LoginAsyncWithHttpInfo (AuthRequestDto credentials);
        /// <summary>
        /// Log out of system
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task LogoutAsync (Guid? xSessionID);

        /// <summary>
        /// Log out of system
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> LogoutAsyncWithHttpInfo (Guid? xSessionID);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SessionApi : ISessionApi
    {
        private Cloud.TTS.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SessionApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SessionApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = Cloud.TTS.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SessionApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SessionApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Cloud.TTS.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Cloud.TTS.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Check session state 
        /// </summary>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <returns>AuthStatusDto</returns>
        public AuthStatusDto Check (Guid? xSessionID)
        {
             ApiResponse<AuthStatusDto> localVarResponse = CheckWithHttpInfo(xSessionID);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Check session state 
        /// </summary>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <returns>ApiResponse of AuthStatusDto</returns>
        public ApiResponse< AuthStatusDto > CheckWithHttpInfo (Guid? xSessionID)
        {
            // verify the required parameter 'xSessionID' is set
            if (xSessionID == null)
                throw new ApiException(400, "Missing required parameter 'xSessionID' when calling SessionApi->Check");

            var localVarPath = "vksession/rest/session";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (xSessionID != null) localVarHeaderParams.Add("X-Session-ID", Configuration.ApiClient.ParameterToString(xSessionID)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Check", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AuthStatusDto>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AuthStatusDto) Configuration.ApiClient.Deserialize(localVarResponse, typeof(AuthStatusDto)));
        }

        /// <summary>
        /// Check session state 
        /// </summary>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <returns>Task of AuthStatusDto</returns>
        public async System.Threading.Tasks.Task<AuthStatusDto> CheckAsync (Guid? xSessionID)
        {
             ApiResponse<AuthStatusDto> localVarResponse = await CheckAsyncWithHttpInfo(xSessionID);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Check session state 
        /// </summary>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <returns>Task of ApiResponse (AuthStatusDto)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<AuthStatusDto>> CheckAsyncWithHttpInfo (Guid? xSessionID)
        {
            // verify the required parameter 'xSessionID' is set
            if (xSessionID == null)
                throw new ApiException(400, "Missing required parameter 'xSessionID' when calling SessionApi->Check");

            var localVarPath = "vksession/rest/session";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (xSessionID != null) localVarHeaderParams.Add("X-Session-ID", Configuration.ApiClient.ParameterToString(xSessionID)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Check", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AuthStatusDto>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AuthStatusDto) Configuration.ApiClient.Deserialize(localVarResponse, typeof(AuthStatusDto)));
        }

        /// <summary>
        /// Get All domains for auth without session 
        /// </summary>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>DomainDto</returns>
        public DomainDto GetDomains ()
        {
             ApiResponse<DomainDto> localVarResponse = GetDomainsWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get All domains for auth without session 
        /// </summary>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of DomainDto</returns>
        public ApiResponse< DomainDto > GetDomainsWithHttpInfo ()
        {

            var localVarPath = "/domains";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetDomains", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DomainDto>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DomainDto) Configuration.ApiClient.Deserialize(localVarResponse, typeof(DomainDto)));
        }

        /// <summary>
        /// Get All domains for auth without session 
        /// </summary>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of DomainDto</returns>
        public async System.Threading.Tasks.Task<DomainDto> GetDomainsAsync ()
        {
             ApiResponse<DomainDto> localVarResponse = await GetDomainsAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get All domains for auth without session 
        /// </summary>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (DomainDto)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DomainDto>> GetDomainsAsyncWithHttpInfo ()
        {

            var localVarPath = "vksession/rest/domains";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetDomains", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DomainDto>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DomainDto) Configuration.ApiClient.Deserialize(localVarResponse, typeof(DomainDto)));
        }

        /// <summary>
        /// Get current user privileges 
        /// </summary>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <param name="body">Module names</param>
        /// <returns>Dictionary&lt;string, Object&gt;</returns>
        public Dictionary<string, Object> GetGrantedPrivileges (Guid? xSessionID, ModuleNamesDto body)
        {
             ApiResponse<Dictionary<string, Object>> localVarResponse = GetGrantedPrivilegesWithHttpInfo(xSessionID, body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get current user privileges 
        /// </summary>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <param name="body">Module names</param>
        /// <returns>ApiResponse of Dictionary&lt;string, Object&gt;</returns>
        public ApiResponse< Dictionary<string, Object> > GetGrantedPrivilegesWithHttpInfo (Guid? xSessionID, ModuleNamesDto body)
        {
            // verify the required parameter 'xSessionID' is set
            if (xSessionID == null)
                throw new ApiException(400, "Missing required parameter 'xSessionID' when calling SessionApi->GetGrantedPrivileges");
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling SessionApi->GetGrantedPrivileges");

            var localVarPath = "vksession/rest/privileges";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (xSessionID != null) localVarHeaderParams.Add("X-Session-ID", Configuration.ApiClient.ParameterToString(xSessionID)); // header parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetGrantedPrivileges", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Dictionary<string, Object>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Dictionary<string, Object>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Dictionary<string, Object>)));
        }

        /// <summary>
        /// Get current user privileges 
        /// </summary>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <param name="body">Module names</param>
        /// <returns>Task of Dictionary&lt;string, Object&gt;</returns>
        public async System.Threading.Tasks.Task<Dictionary<string, Object>> GetGrantedPrivilegesAsync (Guid? xSessionID, ModuleNamesDto body)
        {
             ApiResponse<Dictionary<string, Object>> localVarResponse = await GetGrantedPrivilegesAsyncWithHttpInfo(xSessionID, body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get current user privileges 
        /// </summary>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <param name="body">Module names</param>
        /// <returns>Task of ApiResponse (Dictionary&lt;string, Object&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Dictionary<string, Object>>> GetGrantedPrivilegesAsyncWithHttpInfo (Guid? xSessionID, ModuleNamesDto body)
        {
            // verify the required parameter 'xSessionID' is set
            if (xSessionID == null)
                throw new ApiException(400, "Missing required parameter 'xSessionID' when calling SessionApi->GetGrantedPrivileges");
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling SessionApi->GetGrantedPrivileges");

            var localVarPath = "vksession/rest/privileges";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (xSessionID != null) localVarHeaderParams.Add("X-Session-ID", Configuration.ApiClient.ParameterToString(xSessionID)); // header parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetGrantedPrivileges", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Dictionary<string, Object>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Dictionary<string, Object>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(Dictionary<string, Object>)));
        }

        /// <summary>
        /// Log in to system and obtain session identifier. Pass sessionId in &#39;X-Session-ID&#39; header in all other API requests 
        /// </summary>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="credentials">User&#39;s credentials</param>
        /// <returns>AuthResponseDto</returns>
        public AuthResponseDto Login (AuthRequestDto credentials)
        {
             ApiResponse<AuthResponseDto> localVarResponse = LoginWithHttpInfo(credentials);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Log in to system and obtain session identifier. Pass sessionId in &#39;X-Session-ID&#39; header in all other API requests 
        /// </summary>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="credentials">User&#39;s credentials</param>
        /// <returns>ApiResponse of AuthResponseDto</returns>
        public ApiResponse< AuthResponseDto > LoginWithHttpInfo (AuthRequestDto credentials)
        {
            // verify the required parameter 'credentials' is set
            if (credentials == null)
                throw new ApiException(400, "Missing required parameter 'credentials' when calling SessionApi->Login");

            var localVarPath = "vksession/rest/session";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (credentials != null && credentials.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(credentials); // http body (model) parameter
            }
            else
            {
                localVarPostBody = credentials; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Login", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AuthResponseDto>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AuthResponseDto) Configuration.ApiClient.Deserialize(localVarResponse, typeof(AuthResponseDto)));
        }

        /// <summary>
        /// Log in to system and obtain session identifier. Pass sessionId in &#39;X-Session-ID&#39; header in all other API requests 
        /// </summary>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="credentials">User&#39;s credentials</param>
        /// <returns>Task of AuthResponseDto</returns>
        public async System.Threading.Tasks.Task<AuthResponseDto> LoginAsync (AuthRequestDto credentials)
        {
             ApiResponse<AuthResponseDto> localVarResponse = await LoginAsyncWithHttpInfo(credentials);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Log in to system and obtain session identifier. Pass sessionId in &#39;X-Session-ID&#39; header in all other API requests 
        /// </summary>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="credentials">User&#39;s credentials</param>
        /// <returns>Task of ApiResponse (AuthResponseDto)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<AuthResponseDto>> LoginAsyncWithHttpInfo (AuthRequestDto credentials)
        {
            // verify the required parameter 'credentials' is set
            if (credentials == null)
                throw new ApiException(400, "Missing required parameter 'credentials' when calling SessionApi->Login");

            var localVarPath = "vksession/rest/session";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (credentials != null && credentials.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(credentials); // http body (model) parameter
            }
            else
            {
                localVarPostBody = credentials; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Login", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<AuthResponseDto>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (AuthResponseDto) Configuration.ApiClient.Deserialize(localVarResponse, typeof(AuthResponseDto)));
        }

        /// <summary>
        /// Log out of system 
        /// </summary>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <returns></returns>
        public void Logout (Guid? xSessionID)
        {
             LogoutWithHttpInfo(xSessionID);
        }

        /// <summary>
        /// Log out of system 
        /// </summary>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public ApiResponse<Object> LogoutWithHttpInfo (Guid? xSessionID)
        {
            // verify the required parameter 'xSessionID' is set
            if (xSessionID == null)
                throw new ApiException(400, "Missing required parameter 'xSessionID' when calling SessionApi->Logout");

            var localVarPath = "vksession/rest/session";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (xSessionID != null) localVarHeaderParams.Add("X-Session-ID", Configuration.ApiClient.ParameterToString(xSessionID)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Logout", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

        /// <summary>
        /// Log out of system 
        /// </summary>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task LogoutAsync (Guid? xSessionID)
        {
             await LogoutAsyncWithHttpInfo(xSessionID);

        }

        /// <summary>
        /// Log out of system 
        /// </summary>
        /// <exception cref="Cloud.TTS.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Object>> LogoutAsyncWithHttpInfo (Guid? xSessionID)
        {
            // verify the required parameter 'xSessionID' is set
            if (xSessionID == null)
                throw new ApiException(400, "Missing required parameter 'xSessionID' when calling SessionApi->Logout");

            var localVarPath = "vksession/rest/session";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (xSessionID != null) localVarHeaderParams.Add("X-Session-ID", Configuration.ApiClient.ParameterToString(xSessionID)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Logout", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                null);
        }

    }
}
