/* 
 * TTS documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.1.73
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Cloud.Client;
using Cloud.Client.TTS.Model;

namespace Cloud.Client.TTS.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISynthesizeApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Available languages
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <returns>List&lt;SynthesizeLanguage&gt;</returns>
        List<SynthesizeLanguage> LanguageVoicesSupport (string xSessionId);

        /// <summary>
        /// Available languages
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <returns>ApiResponse of List&lt;SynthesizeLanguage&gt;</returns>
        ApiResponse<List<SynthesizeLanguage>> LanguageVoicesSupportWithHttpInfo (string xSessionId);
        /// <summary>
        /// Synthesize speech from text
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="body">Synthesize param</param>
        /// <returns>SynthesizeResponse</returns>
        SynthesizeResponse Synthesize (string xSessionId, SynthesizeRequest body);

        /// <summary>
        /// Synthesize speech from text
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="body">Synthesize param</param>
        /// <returns>ApiResponse of SynthesizeResponse</returns>
        ApiResponse<SynthesizeResponse> SynthesizeWithHttpInfo (string xSessionId, SynthesizeRequest body);
        /// <summary>
        /// Synthesize speech from text without session
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Synthesize param</param>
        /// <returns>SynthesizeResponse</returns>
        SynthesizeResponse SynthesizeSessionless (SynthesizeSessionlessRequest body);

        /// <summary>
        /// Synthesize speech from text without session
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Synthesize param</param>
        /// <returns>ApiResponse of SynthesizeResponse</returns>
        ApiResponse<SynthesizeResponse> SynthesizeSessionlessWithHttpInfo (SynthesizeSessionlessRequest body);
        /// <summary>
        /// Available languages
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="language">Language name</param>
        /// <returns>List&lt;SynthesizeVoiceType&gt;</returns>
        List<SynthesizeVoiceType> Voices (Guid? xSessionId, string language);

        /// <summary>
        /// Available languages
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="language">Language name</param>
        /// <returns>ApiResponse of List&lt;SynthesizeVoiceType&gt;</returns>
        ApiResponse<List<SynthesizeVoiceType>> VoicesWithHttpInfo (Guid? xSessionId, string language);
        /// <summary>
        /// Get websocket connection param
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="body">Synthesize param</param>
        /// <returns>WebSocketServerConfiguration</returns>
        WebSocketServerConfiguration WebSocketStream (Guid? xSessionId, WebSocketSynthesizeRequest body);

        /// <summary>
        /// Get websocket connection param
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="body">Synthesize param</param>
        /// <returns>ApiResponse of WebSocketServerConfiguration</returns>
        ApiResponse<WebSocketServerConfiguration> WebSocketStreamWithHttpInfo (Guid? xSessionId, WebSocketSynthesizeRequest body);
        /// <summary>
        /// Close transaction
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="xTransactionId">Transaction Id</param>
        /// <returns>CloseTransactionResponse</returns>
        CloseTransactionResponse CloseWebSocketStream (Guid? xSessionId, Guid? xTransactionId);

        /// <summary>
        /// Close transaction
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="xTransactionId">Transaction Id</param>
        /// <returns>ApiResponse of CloseTransactionResponse</returns>
        ApiResponse<CloseTransactionResponse> CloseWebSocketStreamWithHttpInfo(Guid? xSessionId, Guid? xTransactionId);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Available languages
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <returns>Task of List&lt;SynthesizeLanguage&gt;</returns>
        System.Threading.Tasks.Task<List<SynthesizeLanguage>> LanguageVoicesSupportAsync (string xSessionId);

        /// <summary>
        /// Available languages
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <returns>Task of ApiResponse (List&lt;SynthesizeLanguage&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<SynthesizeLanguage>>> LanguageVoicesSupportAsyncWithHttpInfo (string xSessionId);
        /// <summary>
        /// Synthesize speech from text
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="body">Synthesize param</param>
        /// <returns>Task of SynthesizeResponse</returns>
        System.Threading.Tasks.Task<SynthesizeResponse> SynthesizeAsync (string xSessionId, SynthesizeRequest body);

        /// <summary>
        /// Synthesize speech from text
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="body">Synthesize param</param>
        /// <returns>Task of ApiResponse (SynthesizeResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<SynthesizeResponse>> SynthesizeAsyncWithHttpInfo (string xSessionId, SynthesizeRequest body);
        /// <summary>
        /// Synthesize speech from text without session
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Synthesize param</param>
        /// <returns>Task of SynthesizeResponse</returns>
        System.Threading.Tasks.Task<SynthesizeResponse> SynthesizeSessionlessAsync (SynthesizeSessionlessRequest body);

        /// <summary>
        /// Synthesize speech from text without session
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Synthesize param</param>
        /// <returns>Task of ApiResponse (SynthesizeResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<SynthesizeResponse>> SynthesizeSessionlessAsyncWithHttpInfo (SynthesizeSessionlessRequest body);
        /// <summary>
        /// Available languages
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="language">Language name</param>
        /// <returns>Task of List&lt;SynthesizeVoiceType&gt;</returns>
        System.Threading.Tasks.Task<List<SynthesizeVoiceType>> VoicesAsync (Guid? xSessionId, string language);

        /// <summary>
        /// Available languages
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="language">Language name</param>
        /// <returns>Task of ApiResponse (List&lt;SynthesizeVoiceType&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<SynthesizeVoiceType>>> VoicesAsyncWithHttpInfo (Guid? xSessionId, string language);
        /// <summary>
        /// Get websocket connection param
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="body">Synthesize param</param>
        /// <returns>Task of WebSocketServerConfiguration</returns>
        System.Threading.Tasks.Task<WebSocketServerConfiguration> WebSocketStreamAsync (Guid? xSessionId, WebSocketSynthesizeRequest body);

        /// <summary>
        /// Get websocket connection param
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="body">Synthesize param</param>
        /// <returns>Task of ApiResponse (WebSocketServerConfiguration)</returns>
        System.Threading.Tasks.Task<ApiResponse<WebSocketServerConfiguration>> WebSocketStreamAsyncWithHttpInfo (Guid? xSessionId, WebSocketSynthesizeRequest body);
        /// <summary>
        /// Close transaction
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="xTransactionId">Transaction Id</param>
        /// <returns>Task of CloseTransactionResponse</returns>
        System.Threading.Tasks.Task<CloseTransactionResponse> CloseWebSocketStreamAsync(Guid? xSessionId, Guid? xTransactionId);

        /// <summary>
        /// Close transaction
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="xTransactionId">Transaction Id</param>
        /// <returns>Task of ApiResponse (CloseTransactionResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<CloseTransactionResponse>> CloseWebSocketStreamAsyncWithHttpInfo(Guid? xSessionId, Guid? xTransactionId);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SynthesizeApi : ISynthesizeApi
    {
        private Cloud.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="V1Api"/> class.
        /// </summary>
        /// <returns></returns>
        public SynthesizeApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = Cloud.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="V1Api"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SynthesizeApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Cloud.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Cloud.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Available languages 
        /// </summary>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <returns>List&lt;SynthesizeLanguage&gt;</returns>
        public List<SynthesizeLanguage> LanguageVoicesSupport (string xSessionId)
        {
             ApiResponse<List<SynthesizeLanguage>> localVarResponse = LanguageVoicesSupportWithHttpInfo(xSessionId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Available languages 
        /// </summary>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <returns>ApiResponse of List&lt;SynthesizeLanguage&gt;</returns>
        public ApiResponse< List<SynthesizeLanguage> > LanguageVoicesSupportWithHttpInfo (string xSessionId)
        {
            // verify the required parameter 'xSessionId' is set
            if (xSessionId == null)
                throw new ApiException(400, "Missing required parameter 'xSessionId' when calling V1Api->LanguageVoicesSupport");

            var localVarPath = "/v1/languages";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (xSessionId != null) localVarHeaderParams.Add("X-Session-Id", Configuration.ApiClient.ParameterToString(xSessionId)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("LanguageVoicesSupport", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<SynthesizeLanguage>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<SynthesizeLanguage>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<SynthesizeLanguage>)));
        }

        /// <summary>
        /// Available languages 
        /// </summary>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <returns>Task of List&lt;SynthesizeLanguage&gt;</returns>
        public async System.Threading.Tasks.Task<List<SynthesizeLanguage>> LanguageVoicesSupportAsync (string xSessionId)
        {
             ApiResponse<List<SynthesizeLanguage>> localVarResponse = await LanguageVoicesSupportAsyncWithHttpInfo(xSessionId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Available languages 
        /// </summary>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <returns>Task of ApiResponse (List&lt;SynthesizeLanguage&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<SynthesizeLanguage>>> LanguageVoicesSupportAsyncWithHttpInfo (string xSessionId)
        {
            // verify the required parameter 'xSessionId' is set
            if (xSessionId == null)
                throw new ApiException(400, "Missing required parameter 'xSessionId' when calling V1Api->LanguageVoicesSupport");

            var localVarPath = "/v1/languages";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (xSessionId != null) localVarHeaderParams.Add("X-Session-Id", Configuration.ApiClient.ParameterToString(xSessionId)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("LanguageVoicesSupport", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<SynthesizeLanguage>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<SynthesizeLanguage>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<SynthesizeLanguage>)));
        }

        /// <summary>
        /// Synthesize speech from text 
        /// </summary>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="body">Synthesize param</param>
        /// <returns>SynthesizeResponse</returns>
        public SynthesizeResponse Synthesize (string xSessionId, SynthesizeRequest body)
        {
             ApiResponse<SynthesizeResponse> localVarResponse = SynthesizeWithHttpInfo(xSessionId, body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Synthesize speech from text 
        /// </summary>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="body">Synthesize param</param>
        /// <returns>ApiResponse of SynthesizeResponse</returns>
        public ApiResponse< SynthesizeResponse > SynthesizeWithHttpInfo (string xSessionId, SynthesizeRequest body)
        {
            // verify the required parameter 'xSessionId' is set
            if (xSessionId == null)
                throw new ApiException(400, "Missing required parameter 'xSessionId' when calling V1Api->Synthesize");
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling V1Api->Synthesize");

            var localVarPath = "/v1/synthesize";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (xSessionId != null) localVarHeaderParams.Add("X-Session-Id", Configuration.ApiClient.ParameterToString(xSessionId)); // header parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Synthesize", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SynthesizeResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (SynthesizeResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(SynthesizeResponse)));
        }

        /// <summary>
        /// Synthesize speech from text 
        /// </summary>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="body">Synthesize param</param>
        /// <returns>Task of SynthesizeResponse</returns>
        public async System.Threading.Tasks.Task<SynthesizeResponse> SynthesizeAsync (string xSessionId, SynthesizeRequest body)
        {
             ApiResponse<SynthesizeResponse> localVarResponse = await SynthesizeAsyncWithHttpInfo(xSessionId, body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Synthesize speech from text 
        /// </summary>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="body">Synthesize param</param>
        /// <returns>Task of ApiResponse (SynthesizeResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SynthesizeResponse>> SynthesizeAsyncWithHttpInfo (string xSessionId, SynthesizeRequest body)
        {
            // verify the required parameter 'xSessionId' is set
            if (xSessionId == null)
                throw new ApiException(400, "Missing required parameter 'xSessionId' when calling V1Api->Synthesize");
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling V1Api->Synthesize");

            var localVarPath = "/v1/synthesize";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (xSessionId != null) localVarHeaderParams.Add("X-Session-Id", Configuration.ApiClient.ParameterToString(xSessionId)); // header parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Synthesize", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SynthesizeResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (SynthesizeResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(SynthesizeResponse)));
        }

        /// <summary>
        /// Synthesize speech from text without session 
        /// </summary>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Synthesize param</param>
        /// <returns>SynthesizeResponse</returns>
        public SynthesizeResponse SynthesizeSessionless (SynthesizeSessionlessRequest body)
        {
             ApiResponse<SynthesizeResponse> localVarResponse = SynthesizeSessionlessWithHttpInfo(body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Synthesize speech from text without session 
        /// </summary>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Synthesize param</param>
        /// <returns>ApiResponse of SynthesizeResponse</returns>
        public ApiResponse< SynthesizeResponse > SynthesizeSessionlessWithHttpInfo (SynthesizeSessionlessRequest body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling V1Api->SynthesizeSessionless");

            var localVarPath = "/v1/synthesize/sessionless";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SynthesizeSessionless", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SynthesizeResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (SynthesizeResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(SynthesizeResponse)));
        }

        /// <summary>
        /// Synthesize speech from text without session 
        /// </summary>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Synthesize param</param>
        /// <returns>Task of SynthesizeResponse</returns>
        public async System.Threading.Tasks.Task<SynthesizeResponse> SynthesizeSessionlessAsync (SynthesizeSessionlessRequest body)
        {
             ApiResponse<SynthesizeResponse> localVarResponse = await SynthesizeSessionlessAsyncWithHttpInfo(body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Synthesize speech from text without session 
        /// </summary>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="body">Synthesize param</param>
        /// <returns>Task of ApiResponse (SynthesizeResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<SynthesizeResponse>> SynthesizeSessionlessAsyncWithHttpInfo (SynthesizeSessionlessRequest body)
        {
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling V1Api->SynthesizeSessionless");

            var localVarPath = "/v1/synthesize/sessionless";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("SynthesizeSessionless", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<SynthesizeResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (SynthesizeResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(SynthesizeResponse)));
        }

        /// <summary>
        /// Available languages 
        /// </summary>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="language">Language name</param>
        /// <returns>List&lt;SynthesizeVoiceType&gt;</returns>
        public List<SynthesizeVoiceType> Voices (Guid? xSessionId, string language)
        {
             ApiResponse<List<SynthesizeVoiceType>> localVarResponse = VoicesWithHttpInfo(xSessionId, language);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Available languages 
        /// </summary>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="language">Language name</param>
        /// <returns>ApiResponse of List&lt;SynthesizeVoiceType&gt;</returns>
        public ApiResponse< List<SynthesizeVoiceType> > VoicesWithHttpInfo (Guid? xSessionId, string language)
        {
            // verify the required parameter 'xSessionId' is set
            if (xSessionId == null)
                throw new ApiException(400, "Missing required parameter 'xSessionId' when calling V1Api->Voices");
            // verify the required parameter 'language' is set
            if (language == null)
                throw new ApiException(400, "Missing required parameter 'language' when calling V1Api->Voices");

            var localVarPath = "/v1/languages/{language}/voices";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (language != null) localVarPathParams.Add("language", Configuration.ApiClient.ParameterToString(language)); // path parameter
            if (xSessionId != null) localVarHeaderParams.Add("X-Session-Id", Configuration.ApiClient.ParameterToString(xSessionId)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Voices", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<SynthesizeVoiceType>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<SynthesizeVoiceType>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<SynthesizeVoiceType>)));
        }

        /// <summary>
        /// Available languages 
        /// </summary>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="language">Language name</param>
        /// <returns>Task of List&lt;SynthesizeVoiceType&gt;</returns>
        public async System.Threading.Tasks.Task<List<SynthesizeVoiceType>> VoicesAsync (Guid? xSessionId, string language)
        {
             ApiResponse<List<SynthesizeVoiceType>> localVarResponse = await VoicesAsyncWithHttpInfo(xSessionId, language);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Available languages 
        /// </summary>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="language">Language name</param>
        /// <returns>Task of ApiResponse (List&lt;SynthesizeVoiceType&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<SynthesizeVoiceType>>> VoicesAsyncWithHttpInfo (Guid? xSessionId, string language)
        {
            // verify the required parameter 'xSessionId' is set
            if (xSessionId == null)
                throw new ApiException(400, "Missing required parameter 'xSessionId' when calling V1Api->Voices");
            // verify the required parameter 'language' is set
            if (language == null)
                throw new ApiException(400, "Missing required parameter 'language' when calling V1Api->Voices");

            var localVarPath = "/v1/languages/{language}/voices";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (language != null) localVarPathParams.Add("language", Configuration.ApiClient.ParameterToString(language)); // path parameter
            if (xSessionId != null) localVarHeaderParams.Add("X-Session-Id", Configuration.ApiClient.ParameterToString(xSessionId)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Voices", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<SynthesizeVoiceType>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<SynthesizeVoiceType>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<SynthesizeVoiceType>)));
        }

        /// <summary>
        /// Get websocket connection param 
        /// </summary>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="body">Synthesize param</param>
        /// <returns>WebSocketServerConfiguration</returns>
        public WebSocketServerConfiguration WebSocketStream (Guid? xSessionId, WebSocketSynthesizeRequest body)
        {
             ApiResponse<WebSocketServerConfiguration> localVarResponse = WebSocketStreamWithHttpInfo(xSessionId, body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get websocket connection param 
        /// </summary>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="body">Synthesize param</param>
        /// <returns>ApiResponse of WebSocketServerConfiguration</returns>
        public ApiResponse< WebSocketServerConfiguration > WebSocketStreamWithHttpInfo (Guid? xSessionId, WebSocketSynthesizeRequest body)
        {
            // verify the required parameter 'xSessionId' is set
            if (xSessionId == null)
                throw new ApiException(400, "Missing required parameter 'xSessionId' when calling V1Api->WebSocketStream");
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling V1Api->WebSocketStream");

            var localVarPath = "/v1/synthesize/stream";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (xSessionId != null) localVarHeaderParams.Add("X-Session-Id", Configuration.ApiClient.ParameterToString(xSessionId)); // header parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("WebSocketStream", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<WebSocketServerConfiguration>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (WebSocketServerConfiguration) Configuration.ApiClient.Deserialize(localVarResponse, typeof(WebSocketServerConfiguration)));
        }

        /// <summary>
        /// Get websocket connection param 
        /// </summary>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="body">Synthesize param</param>
        /// <returns>Task of WebSocketServerConfiguration</returns>
        public async System.Threading.Tasks.Task<WebSocketServerConfiguration> WebSocketStreamAsync (Guid? xSessionId, WebSocketSynthesizeRequest body)
        {
             ApiResponse<WebSocketServerConfiguration> localVarResponse = await WebSocketStreamAsyncWithHttpInfo(xSessionId, body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get websocket connection param 
        /// </summary>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="body">Synthesize param</param>
        /// <returns>Task of ApiResponse (WebSocketServerConfiguration)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<WebSocketServerConfiguration>> WebSocketStreamAsyncWithHttpInfo (Guid? xSessionId, WebSocketSynthesizeRequest body)
        {
            // verify the required parameter 'xSessionId' is set
            if (xSessionId == null)
                throw new ApiException(400, "Missing required parameter 'xSessionId' when calling V1Api->WebSocketStream");
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling V1Api->WebSocketStream");

            var localVarPath = "/v1/synthesize/stream";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (xSessionId != null) localVarHeaderParams.Add("X-Session-Id", Configuration.ApiClient.ParameterToString(xSessionId)); // header parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("WebSocketStream", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<WebSocketServerConfiguration>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (WebSocketServerConfiguration) Configuration.ApiClient.Deserialize(localVarResponse, typeof(WebSocketServerConfiguration)));
        }

        /// <summary>
        /// Close transaction 
        /// </summary>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="xTransactionId">Transaction Id</param>
        /// <returns>CloseTransactionResponse</returns>
        public CloseTransactionResponse CloseWebSocketStream (Guid? xSessionId, Guid? xTransactionId)
        {
             ApiResponse<CloseTransactionResponse> localVarResponse = CloseWebSocketStreamWithHttpInfo(xSessionId, xTransactionId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Close transaction 
        /// </summary>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="xTransactionId">Transaction Id</param>
        /// <returns>ApiResponse of CloseTransactionResponse</returns>
        public ApiResponse< CloseTransactionResponse > CloseWebSocketStreamWithHttpInfo(Guid? xSessionId, Guid? xTransactionId)
        {
            // verify the required parameter 'xSessionId' is set
            if (xSessionId == null)
                throw new ApiException(400, "Missing required parameter 'xSessionId' when calling V1Api-> CloseWebSocketStream");
            // verify the required parameter 'xTransactionId' is set
            if (xTransactionId == null)
                throw new ApiException(400, "Missing required parameter 'xTransactionId' when calling V1Api-> CloseWebSocketStream");

            var localVarPath = "/v1/synthesize/stream";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (xSessionId != null) localVarHeaderParams.Add("X-Session-Id", Configuration.ApiClient.ParameterToString(xSessionId)); // header parameter
            if (xTransactionId != null) localVarHeaderParams.Add("X-Transaction-Id", Configuration.ApiClient.ParameterToString(xTransactionId)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CloseWebSocketStream", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CloseTransactionResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (CloseTransactionResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(CloseTransactionResponse)));
        }

        /// <summary>
        /// Close transaction 
        /// </summary>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="xTransactionId">Transaction Id</param>
        /// <returns>Task of CloseTransactionResponse</returns>
        public async System.Threading.Tasks.Task<CloseTransactionResponse> CloseWebSocketStreamAsync(Guid? xSessionId, Guid? xTransactionId)
        {
             ApiResponse<CloseTransactionResponse> localVarResponse = await CloseWebSocketStreamAsyncWithHttpInfo(xSessionId, xTransactionId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Close transaction 
        /// </summary>
        /// <exception cref="Cloud.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="xTransactionId">Transaction Id</param>
        /// <returns>Task of ApiResponse (CloseTransactionResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<CloseTransactionResponse>> CloseWebSocketStreamAsyncWithHttpInfo(Guid? xSessionId, Guid? xTransactionId)
        {
            // verify the required parameter 'xSessionId' is set
            if (xSessionId == null)
                throw new ApiException(400, "Missing required parameter 'xSessionId' when calling V1Api->CloseWebSocketStream");
            // verify the required parameter 'xTransactionId' is set
            if (xTransactionId == null)
                throw new ApiException(400, "Missing required parameter 'xTransactionId' when calling V1Api->CloseWebSocketStream");

            var localVarPath = "/v1/synthesize/stream";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (xSessionId != null) localVarHeaderParams.Add("X-Session-Id", Configuration.ApiClient.ParameterToString(xSessionId)); // header parameter
            if (xTransactionId != null) localVarHeaderParams.Add("X-Transaction-Id", Configuration.ApiClient.ParameterToString(xTransactionId)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.DELETE, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("CloseWebSocketStream", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<CloseTransactionResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (CloseTransactionResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(CloseTransactionResponse)));
        }

    }
}
