/* 
 * ASR documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using Cloud.ASR.Client;
using Cloud.ASR.Model;

namespace Cloud.ASR.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IPackagesApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get all available packages
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.ASR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <returns>List&lt;PackageDto&gt;</returns>
        List<PackageDto> GetAvailablePackages (Guid? xSessionID);

        /// <summary>
        /// Get all available packages
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.ASR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <returns>ApiResponse of List&lt;PackageDto&gt;</returns>
        ApiResponse<List<PackageDto>> GetAvailablePackagesWithHttpInfo (Guid? xSessionID);
        /// <summary>
        /// Load package
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.ASR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <param name="packageId">Package name</param>
        /// <returns>StatusDto</returns>
        StatusDto Load (Guid? xSessionID, string packageId);

        /// <summary>
        /// Load package
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.ASR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <param name="packageId">Package name</param>
        /// <returns>ApiResponse of StatusDto</returns>
        ApiResponse<StatusDto> LoadWithHttpInfo (Guid? xSessionID, string packageId);
        /// <summary>
        /// Unload package
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.ASR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <param name="packageId">Package name</param>
        /// <returns>StatusDto</returns>
        StatusDto Unload (Guid? xSessionID, string packageId);

        /// <summary>
        /// Unload package
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.ASR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <param name="packageId">Package name</param>
        /// <returns>ApiResponse of StatusDto</returns>
        ApiResponse<StatusDto> UnloadWithHttpInfo (Guid? xSessionID, string packageId);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Get all available packages
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.ASR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <returns>Task of List&lt;PackageDto&gt;</returns>
        System.Threading.Tasks.Task<List<PackageDto>> GetAvailablePackagesAsync (Guid? xSessionID);

        /// <summary>
        /// Get all available packages
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.ASR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <returns>Task of ApiResponse (List&lt;PackageDto&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<PackageDto>>> GetAvailablePackagesAsyncWithHttpInfo (Guid? xSessionID);
        /// <summary>
        /// Load package
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.ASR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <param name="packageId">Package name</param>
        /// <returns>Task of StatusDto</returns>
        System.Threading.Tasks.Task<StatusDto> LoadAsync (Guid? xSessionID, string packageId);

        /// <summary>
        /// Load package
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.ASR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <param name="packageId">Package name</param>
        /// <returns>Task of ApiResponse (StatusDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<StatusDto>> LoadAsyncWithHttpInfo (Guid? xSessionID, string packageId);
        /// <summary>
        /// Unload package
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.ASR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <param name="packageId">Package name</param>
        /// <returns>Task of StatusDto</returns>
        System.Threading.Tasks.Task<StatusDto> UnloadAsync (Guid? xSessionID, string packageId);

        /// <summary>
        /// Unload package
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Cloud.ASR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <param name="packageId">Package name</param>
        /// <returns>Task of ApiResponse (StatusDto)</returns>
        System.Threading.Tasks.Task<ApiResponse<StatusDto>> UnloadAsyncWithHttpInfo (Guid? xSessionID, string packageId);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class PackagesApi : IPackagesApi
    {
        private Cloud.ASR.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="PackagesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public PackagesApi(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = Cloud.ASR.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PackagesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public PackagesApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = Cloud.ASR.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Cloud.ASR.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Get all available packages 
        /// </summary>
        /// <exception cref="Cloud.ASR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <returns>List&lt;PackageDto&gt;</returns>
        public List<PackageDto> GetAvailablePackages (Guid? xSessionID)
        {
             ApiResponse<List<PackageDto>> localVarResponse = GetAvailablePackagesWithHttpInfo(xSessionID);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get all available packages 
        /// </summary>
        /// <exception cref="Cloud.ASR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <returns>ApiResponse of List&lt;PackageDto&gt;</returns>
        public ApiResponse< List<PackageDto> > GetAvailablePackagesWithHttpInfo (Guid? xSessionID)
        {
            // verify the required parameter 'xSessionID' is set
            if (xSessionID == null)
                throw new ApiException(400, "Missing required parameter 'xSessionID' when calling PackagesApi->GetAvailablePackages");

            var localVarPath = "vkasr/rest/v1/packages/available";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (xSessionID != null) localVarHeaderParams.Add("X-Session-ID", Configuration.ApiClient.ParameterToString(xSessionID)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAvailablePackages", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<PackageDto>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<PackageDto>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<PackageDto>)));
        }

        /// <summary>
        /// Get all available packages 
        /// </summary>
        /// <exception cref="Cloud.ASR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <returns>Task of List&lt;PackageDto&gt;</returns>
        public async System.Threading.Tasks.Task<List<PackageDto>> GetAvailablePackagesAsync (Guid? xSessionID)
        {
             ApiResponse<List<PackageDto>> localVarResponse = await GetAvailablePackagesAsyncWithHttpInfo(xSessionID);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get all available packages 
        /// </summary>
        /// <exception cref="Cloud.ASR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <returns>Task of ApiResponse (List&lt;PackageDto&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<PackageDto>>> GetAvailablePackagesAsyncWithHttpInfo (Guid? xSessionID)
        {
            // verify the required parameter 'xSessionID' is set
            if (xSessionID == null)
                throw new ApiException(400, "Missing required parameter 'xSessionID' when calling PackagesApi->GetAvailablePackages");

            var localVarPath = "vkasr/rest/v1/packages/available";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (xSessionID != null) localVarHeaderParams.Add("X-Session-ID", Configuration.ApiClient.ParameterToString(xSessionID)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAvailablePackages", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<PackageDto>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<PackageDto>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<PackageDto>)));
        }

        /// <summary>
        /// Load package 
        /// </summary>
        /// <exception cref="Cloud.ASR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <param name="packageId">Package name</param>
        /// <returns>StatusDto</returns>
        public StatusDto Load (Guid? xSessionID, string packageId)
        {
             ApiResponse<StatusDto> localVarResponse = LoadWithHttpInfo(xSessionID, packageId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Load package 
        /// </summary>
        /// <exception cref="Cloud.ASR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <param name="packageId">Package name</param>
        /// <returns>ApiResponse of StatusDto</returns>
        public ApiResponse< StatusDto > LoadWithHttpInfo (Guid? xSessionID, string packageId)
        {
            // verify the required parameter 'xSessionID' is set
            if (xSessionID == null)
                throw new ApiException(400, "Missing required parameter 'xSessionID' when calling PackagesApi->Load");
            // verify the required parameter 'packageId' is set
            if (packageId == null)
                throw new ApiException(400, "Missing required parameter 'packageId' when calling PackagesApi->Load");

            var localVarPath = "vkasr/rest/v1/packages/{packageId}/load";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (packageId != null) localVarPathParams.Add("packageId", Configuration.ApiClient.ParameterToString(packageId)); // path parameter
            if (xSessionID != null) localVarHeaderParams.Add("X-Session-ID", Configuration.ApiClient.ParameterToString(xSessionID)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Load", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<StatusDto>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (StatusDto) Configuration.ApiClient.Deserialize(localVarResponse, typeof(StatusDto)));
        }

        /// <summary>
        /// Load package 
        /// </summary>
        /// <exception cref="Cloud.ASR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <param name="packageId">Package name</param>
        /// <returns>Task of StatusDto</returns>
        public async System.Threading.Tasks.Task<StatusDto> LoadAsync (Guid? xSessionID, string packageId)
        {
             ApiResponse<StatusDto> localVarResponse = await LoadAsyncWithHttpInfo(xSessionID, packageId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Load package 
        /// </summary>
        /// <exception cref="Cloud.ASR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <param name="packageId">Package name</param>
        /// <returns>Task of ApiResponse (StatusDto)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<StatusDto>> LoadAsyncWithHttpInfo (Guid? xSessionID, string packageId)
        {
            // verify the required parameter 'xSessionID' is set
            if (xSessionID == null)
                throw new ApiException(400, "Missing required parameter 'xSessionID' when calling PackagesApi->Load");
            // verify the required parameter 'packageId' is set
            if (packageId == null)
                throw new ApiException(400, "Missing required parameter 'packageId' when calling PackagesApi->Load");

            var localVarPath = "vkasr/rest/v1/packages/{packageId}/load";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (packageId != null) localVarPathParams.Add("packageId", Configuration.ApiClient.ParameterToString(packageId)); // path parameter
            if (xSessionID != null) localVarHeaderParams.Add("X-Session-ID", Configuration.ApiClient.ParameterToString(xSessionID)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Load", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<StatusDto>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (StatusDto) Configuration.ApiClient.Deserialize(localVarResponse, typeof(StatusDto)));
        }

        /// <summary>
        /// Unload package 
        /// </summary>
        /// <exception cref="Cloud.ASR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <param name="packageId">Package name</param>
        /// <returns>StatusDto</returns>
        public StatusDto Unload (Guid? xSessionID, string packageId)
        {
             ApiResponse<StatusDto> localVarResponse = UnloadWithHttpInfo(xSessionID, packageId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Unload package 
        /// </summary>
        /// <exception cref="Cloud.ASR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <param name="packageId">Package name</param>
        /// <returns>ApiResponse of StatusDto</returns>
        public ApiResponse< StatusDto > UnloadWithHttpInfo (Guid? xSessionID, string packageId)
        {
            // verify the required parameter 'xSessionID' is set
            if (xSessionID == null)
                throw new ApiException(400, "Missing required parameter 'xSessionID' when calling PackagesApi->Unload");
            // verify the required parameter 'packageId' is set
            if (packageId == null)
                throw new ApiException(400, "Missing required parameter 'packageId' when calling PackagesApi->Unload");

            var localVarPath = "vkasr/rest/v1/packages/{packageId}/unload";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (packageId != null) localVarPathParams.Add("packageId", Configuration.ApiClient.ParameterToString(packageId)); // path parameter
            if (xSessionID != null) localVarHeaderParams.Add("X-Session-ID", Configuration.ApiClient.ParameterToString(xSessionID)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Unload", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<StatusDto>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (StatusDto) Configuration.ApiClient.Deserialize(localVarResponse, typeof(StatusDto)));
        }

        /// <summary>
        /// Unload package 
        /// </summary>
        /// <exception cref="Cloud.ASR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <param name="packageId">Package name</param>
        /// <returns>Task of StatusDto</returns>
        public async System.Threading.Tasks.Task<StatusDto> UnloadAsync (Guid? xSessionID, string packageId)
        {
             ApiResponse<StatusDto> localVarResponse = await UnloadAsyncWithHttpInfo(xSessionID, packageId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Unload package 
        /// </summary>
        /// <exception cref="Cloud.ASR.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionID">Session identifier</param>
        /// <param name="packageId">Package name</param>
        /// <returns>Task of ApiResponse (StatusDto)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<StatusDto>> UnloadAsyncWithHttpInfo (Guid? xSessionID, string packageId)
        {
            // verify the required parameter 'xSessionID' is set
            if (xSessionID == null)
                throw new ApiException(400, "Missing required parameter 'xSessionID' when calling PackagesApi->Unload");
            // verify the required parameter 'packageId' is set
            if (packageId == null)
                throw new ApiException(400, "Missing required parameter 'packageId' when calling PackagesApi->Unload");

            var localVarPath = "vkasr/rest/v1/packages/{packageId}/unload";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json;charset=UTF-8"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (packageId != null) localVarPathParams.Add("packageId", Configuration.ApiClient.ParameterToString(packageId)); // path parameter
            if (xSessionID != null) localVarHeaderParams.Add("X-Session-ID", Configuration.ApiClient.ParameterToString(xSessionID)); // header parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Unload", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<StatusDto>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (StatusDto) Configuration.ApiClient.Deserialize(localVarResponse, typeof(StatusDto)));
        }

    }
}
