/* 
 * Diarization documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.1.73
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IV1Api : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Diarization speech from sample
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="body">Diarization param</param>
        /// <returns>DiarizationResponse</returns>
        DiarizationResponse Diarization (string xSessionId, DiarizationParam body);

        /// <summary>
        /// Diarization speech from sample
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="body">Diarization param</param>
        /// <returns>ApiResponse of DiarizationResponse</returns>
        ApiResponse<DiarizationResponse> DiarizationWithHttpInfo (string xSessionId, DiarizationParam body);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Diarization speech from sample
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="body">Diarization param</param>
        /// <returns>Task of DiarizationResponse</returns>
        System.Threading.Tasks.Task<DiarizationResponse> DiarizationAsync (string xSessionId, DiarizationParam body);

        /// <summary>
        /// Diarization speech from sample
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="body">Diarization param</param>
        /// <returns>Task of ApiResponse (DiarizationResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<DiarizationResponse>> DiarizationAsyncWithHttpInfo (string xSessionId, DiarizationParam body);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class V1Api : IV1Api
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="V1Api"/> class.
        /// </summary>
        /// <returns></returns>
        public V1Api(String basePath)
        {
            this.Configuration = new Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="V1Api"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public V1Api(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Diarization speech from sample 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="body">Diarization param</param>
        /// <returns>DiarizationResponse</returns>
        public DiarizationResponse Diarization (string xSessionId, DiarizationParam body)
        {
             ApiResponse<DiarizationResponse> localVarResponse = DiarizationWithHttpInfo(xSessionId, body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Diarization speech from sample 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="body">Diarization param</param>
        /// <returns>ApiResponse of DiarizationResponse</returns>
        public ApiResponse< DiarizationResponse > DiarizationWithHttpInfo (string xSessionId, DiarizationParam body)
        {
            // verify the required parameter 'xSessionId' is set
            if (xSessionId == null)
                throw new ApiException(400, "Missing required parameter 'xSessionId' when calling V1Api->Diarization");
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling V1Api->Diarization");

            var localVarPath = "/v1/diarization";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (xSessionId != null) localVarHeaderParams.Add("X-Session-Id", Configuration.ApiClient.ParameterToString(xSessionId)); // header parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Diarization", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DiarizationResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DiarizationResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(DiarizationResponse)));
        }

        /// <summary>
        /// Diarization speech from sample 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="body">Diarization param</param>
        /// <returns>Task of DiarizationResponse</returns>
        public async System.Threading.Tasks.Task<DiarizationResponse> DiarizationAsync (string xSessionId, DiarizationParam body)
        {
             ApiResponse<DiarizationResponse> localVarResponse = await DiarizationAsyncWithHttpInfo(xSessionId, body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Diarization speech from sample 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="xSessionId">Session identifier</param>
        /// <param name="body">Diarization param</param>
        /// <returns>Task of ApiResponse (DiarizationResponse)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<DiarizationResponse>> DiarizationAsyncWithHttpInfo (string xSessionId, DiarizationParam body)
        {
            // verify the required parameter 'xSessionId' is set
            if (xSessionId == null)
                throw new ApiException(400, "Missing required parameter 'xSessionId' when calling V1Api->Diarization");
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling V1Api->Diarization");

            var localVarPath = "/v1/diarization";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (xSessionId != null) localVarHeaderParams.Add("X-Session-Id", Configuration.ApiClient.ParameterToString(xSessionId)); // header parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("Diarization", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<DiarizationResponse>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (DiarizationResponse) Configuration.ApiClient.Deserialize(localVarResponse, typeof(DiarizationResponse)));
        }

    }
}
