/* 
 * Diarization documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.1.73
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Audio
    /// </summary>
    [DataContract]
    public partial class Audio :  IEquatable<Audio>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Audio" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Audio() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Audio" /> class.
        /// </summary>
        /// <param name="Data">Audio in base64 for diarization (required).</param>
        /// <param name="Mime">Mime type of audio. Possible value: audio/alaw, audio/mulaw, audio/s16be, audio/wav (required).</param>
        public Audio(string Data = default(string), string Mime = default(string))
        {
            // to ensure "Data" is required (not null)
            if (Data == null)
            {
                throw new InvalidDataException("Data is a required property for Audio and cannot be null");
            }
            else
            {
                this.Data = Data;
            }
            // to ensure "Mime" is required (not null)
            if (Mime == null)
            {
                throw new InvalidDataException("Mime is a required property for Audio and cannot be null");
            }
            else
            {
                this.Mime = Mime;
            }
        }
        
        /// <summary>
        /// Audio in base64 for diarization
        /// </summary>
        /// <value>Audio in base64 for diarization</value>
        [DataMember(Name="data", EmitDefaultValue=false)]
        public string Data { get; set; }

        /// <summary>
        /// Mime type of audio. Possible value: audio/alaw, audio/mulaw, audio/s16be, audio/wav
        /// </summary>
        /// <value>Mime type of audio. Possible value: audio/alaw, audio/mulaw, audio/s16be, audio/wav</value>
        [DataMember(Name="mime", EmitDefaultValue=false)]
        public string Mime { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Audio {\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Mime: ").Append(Mime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Audio);
        }

        /// <summary>
        /// Returns true if Audio instances are equal
        /// </summary>
        /// <param name="input">Instance of Audio to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Audio input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Data == input.Data ||
                    (this.Data != null &&
                    this.Data.Equals(input.Data))
                ) && 
                (
                    this.Mime == input.Mime ||
                    (this.Mime != null &&
                    this.Mime.Equals(input.Mime))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Data != null)
                    hashCode = hashCode * 59 + this.Data.GetHashCode();
                if (this.Mime != null)
                    hashCode = hashCode * 59 + this.Mime.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
