/* 
 * Diarization documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.1.73
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// DiarizationResult
    /// </summary>
    [DataContract]
    public partial class DiarizationResult :  IEquatable<DiarizationResult>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DiarizationResult" /> class.
        /// </summary>
        /// <param name="Speakers">Speakers.</param>
        public DiarizationResult(List<Speaker> Speakers = default(List<Speaker>))
        {
            this.Speakers = Speakers;
        }
        
        /// <summary>
        /// Gets or Sets Speakers
        /// </summary>
        [DataMember(Name="speakers", EmitDefaultValue=false)]
        public List<Speaker> Speakers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DiarizationResult {\n");
            sb.Append("  Speakers: ").Append(Speakers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DiarizationResult);
        }

        /// <summary>
        /// Returns true if DiarizationResult instances are equal
        /// </summary>
        /// <param name="input">Instance of DiarizationResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DiarizationResult input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Speakers == input.Speakers ||
                    this.Speakers != null &&
                    this.Speakers.SequenceEqual(input.Speakers)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Speakers != null)
                    hashCode = hashCode * 59 + this.Speakers.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
